import type { RoadmapNode } from "./types";

export const DEFAULT_ROADMAP: RoadmapNode = {
  id: "root",
  title: "$1B net worth (liquid + equity, risk-adjusted)",
  confidencePct: 12,
  milestonePct: 4,
  timelineNote: "Horizon: multi-decade. Revisit quarterly.",
  assumptions: ["Regulatory posture remains navigable.", "Dental procurement infra consolidates EU-wide.", "Ownership dilution disciplined."],
  blockers: ["Scale proof on retention beyond early cohort.", "Capital structure for EU expansion unsettled."],
  notes: "Work backwards only from outcomes you can materially influence.",
  metrics: ["Personal liquidity", "Post-tax equity value", "Dentago diluted stake"],
  children: [
    {
      id: "n15",
      title: "Hold ~15% of $7B strategic acquirer / IPO outcome",
      confidencePct: 18,
      milestonePct: 8,
      timelineNote: "Requires category-defining infra position.",
      assumptions: ["Liquidity event at strategic multiple.", "No catastrophic cap table resets."],
      blockers: ["Category narrative not yet unmistakable.", "Procurement liquidity depth uncertain."],
      notes: "",
      metrics: ["Fully diluted %", "Option exercise cost", "Lock-up timelines"],
      children: [
        {
          id: "arr150",
          title: "Dentago → $150M ARR procurement flywheel",
          confidencePct: 22,
          milestonePct: 11,
          timelineNote: "5–15 year glide path depending on land-and-expand tempo.",
          assumptions: ["Sticky basket behavior + supplier reliability.", "Clinic density in core geographies."],
          blockers: ["Supplier SLAs uneven at scale.", "Competitive tenders from distributors."],
          notes: "",
          metrics: ["NRR", "GMV retention", "Active SKUs/procurement events"],
          children: [
            {
              id: "eu-infra",
              title: "Europe-wide procurement infra (legal, logistics, integrations)",
              confidencePct: 28,
              milestonePct: 14,
              timelineNote: "After UK repeatable motion.",
              assumptions: ["Standardized onboarding playbooks.", "Banking + VAT compliance automated."],
              blockers: ["Localization cost curve.", "Hiring sequencing for BD + ops."],
              notes: "",
              metrics: ["Integration uptime", "Time-to-live per supplier"],
              children: [
                {
                  id: "uk",
                  title: "UK dominance: density + reliability leadership",
                  confidencePct: 34,
                  milestonePct: 22,
                  timelineNote: "18–48 month operational focus.",
                  assumptions: ["Clinical trust via consistency > novelty.", "Data moat via usage."],
                  blockers: ["Churn disguised as price shopping.", "Competitor subsidy campaigns."],
                  notes: "",
                  metrics: ["Active clinics MoM", "D14 reorder", "Retention cohorts"],
                  children: [
                    {
                      id: "habit",
                      title: "Habitual procurement on-platform (sticky basket loops)",
                      confidencePct: 41,
                      milestonePct: 31,
                      timelineNote: "Continuous product iteration.",
                      assumptions: ["Checkout friction negligible.", "Search relevance best-in-sector."],
                      blockers: ["Edge-case SKUs routed off-platform.", "Price drift erodes trust."],
                      notes: "",
                      metrics: ["Share of wallet proxy", "Search-to-cart latency"],
                      children: [
                        {
                          id: "pmf50",
                          title: "50 active clinics — durable PMF signal",
                          confidencePct: 52,
                          milestonePct: 48,
                          timelineNote: "Near-term existential gate.",
                          assumptions: ["Willingness to pay holds.", "Unit economics workable at this scale."],
                          blockers: ["False signal from subsidy-led growth.", "Ops bottlenecks at clinic onboarding."],
                          notes: "Validation must be evidenced by retained GMV — not signup vanity.",
                          metrics: ["Net revenue churn", "Cohort reorder curves"],
                          children: [
                            {
                              id: "validate",
                              title: "Prove PMF: retention + reorder before scaling spend",
                              confidencePct: 58,
                              milestonePct: 55,
                              timelineNote: "Now.",
                              assumptions: ["Instrumentation honest.", "Founder-led sales quality."],
                              blockers: ["Optimism bias in pipeline.", "Under-counting infra debt."],
                              notes: "",
                              metrics: ["Outreach reply rate vs win rate", "Time to second order"],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
