/**
 * Outreach templates (team copy of record: Dentago OS → Templates tab).
 * Originally sourced from Dentago Obsidian notes: Outreach Templates.md and
 * Templates/Dentago — Outreach demo watch.md. Update this file when templates change.
 */

export type TemplateAudience = "clinic" | "supplier" | "press";

export type TemplateChannel = "email" | "linkedin" | "social" | "mixed";

export interface OutreachTemplate {
  id: string;
  /** Short label in the list */
  title: string;
  /** For the “which do I send?” picker */
  pickerHint: string;
  groupId: OutreachTemplateGroupId;
  audience: TemplateAudience | "internal";
  channel: TemplateChannel;
  whenToUse: string;
  subject?: string;
  body: string;
  /** Thresholds / policy — show prominently */
  prerequisites?: string[];
  warnings?: string[];
}

export type OutreachTemplateGroupId =
  | "start_here"
  | "clinic_email"
  | "clinic_demo_watch"
  | "linkedin"
  | "supplier"
  | "press"
  | "playbook";

export interface OutreachTemplateGroup {
  id: OutreachTemplateGroupId;
  title: string;
  description: string;
  emoji: string;
  sort: number;
}

export const OUTREACH_TEMPLATE_GROUPS: OutreachTemplateGroup[] = [
  {
    id: "start_here",
    title: "Start here",
    description: "Read once — gates and how to choose a template.",
    emoji: "🧭",
    sort: 0,
  },
  {
    id: "clinic_email",
    title: "Clinics · email",
    description: "Cold batch, follow-ups, demo booked, referrals.",
    emoji: "🏥",
    sort: 1,
  },
  {
    id: "clinic_demo_watch",
    title: "Clinics · demo link",
    description: "Video-first outreach (dentago.co.uk/watch) — low friction.",
    emoji: "▶️",
    sort: 2,
  },
  {
    id: "linkedin",
    title: "LinkedIn",
    description: "DMs and weekly building-in-public post.",
    emoji: "💼",
    sort: 3,
  },
  {
    id: "supplier",
    title: "Suppliers",
    description: "First touch, leverage, warm technical booking.",
    emoji: "📦",
    sort: 4,
  },
  {
    id: "press",
    title: "Press & media",
    description: "Journalists at launch.",
    emoji: "📰",
    sort: 5,
  },
  {
    id: "playbook",
    title: "Playbook notes",
    description: "Subject lines, timing, disciplines — internal rules.",
    emoji: "✅",
    sort: 6,
  },
];

export const OUTREACH_TEMPLATES: OutreachTemplate[] = [
  {
    id: "gates",
    title: "Who gets which outreach?",
    pickerHint: "Read before sending anything externally.",
    groupId: "start_here",
    audience: "internal",
    channel: "mixed",
    whenToUse: "First day / onboarding — know the thresholds before copying a template.",
    body: [
      "CLINICS",
      "• Clinic cold + follow-ups: anytime you’re talking to practices (no GMV gate on these templates themselves).",
      "• Paragraph-one discipline for cold clinic email: say clearly free for the practice; centre their time and procurement pain before product detail.",
      "• Demo-first swipe (dentago.co.uk/watch): use when you want a low-friction next step instead of insisting on a call.",
      "",
      "SUPPLIERS",
      "• Do not use Supplier A/B until 50+ active clinics (company policy).",
      "• Henry Schein / Kent Express “leverage” style (Supplier B): not until 200+ clinics with real GMV data.",
      "• Supplier C (book 20 min): use after they’ve engaged — details, integration, NHS/framework, EDI thread.",
      "",
      "PRESS",
      "• Journalist template: launch / press moments — not everyday sales.",
      "",
      "HYGIENE",
      "• Swap every [bracket] before send. Personalise opener where possible.",
      "• Prefer one primary CTA per email (calls to action multiply friction).",
    ].join("\n"),
    warnings: ["When in doubt, ask Mercier or check Approvals tab for exceptional sends."],
  },
  {
    id: "clinic_EMAIL_01_apollo",
    title: "Clinic Email 1 — Cold (Apollo / LinkedIn scrape)",
    pickerHint: "First email · you have first name + practice · bold WhatsApp CTA.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse:
      "First contact with decision-makers from Apollo, LinkedIn, or lead scrapers. Batch 5 style (Apollo, Apr 2026).",
    subject: "Only open this if cutting supplies cost is a priority...",
    body: [
      "Hi [First Name],",
      "",
      "Most dental practices are spending hours every week logging into 4–5 supplier sites, comparing prices manually, and placing separate orders with each one.",
      "",
      "Dentago fixes that. One place to search every supplier you already use, see prices side by side, and place one order. Takes 5 minutes to set up and it's completely free for practices. (Btw we integrate your existing supplier accounts to get your negotiated prices).",
      "",
      "If saving on supply costs and cutting down admin time sounds useful, why not join the 200+ dental clinics that are already implementing Dentago? (May as well join the party and save thousands annually on supplies eh?)",
      "",
      "Here's my WhatsApp — +447466 607116. Happy to get you set up as soon as you drop me a message!",
      "",
      "No credit card required — we do NOT charge clinics. We take our fee from the suppliers we work with.",
      "",
      "Mercier,",
      "Founder @ Dentago",
      "www.dentago.co.uk",
    ].join("\n"),
    warnings: ["Update clinic count (“200+”) if marketing asks for factual accuracy.", "Heavy WhatsApp CTA — only if that’s still the preferred funnel."],
  },
  {
    id: "clinic_EMAIL_01B_resend",
    title: "Clinic Email 1B — Cold (Resend batch)",
    pickerHint: "Mass send · personalised intro line per practice · asks for 15-min walkthrough.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "Batches 1–3 mass cold outreach via Resend. Personalised compliment line per clinic.",
    subject: "Varies — e.g. “[Practice Name] — quick question” / “Spotted your practice in [City] — quick question”",
    body: [
      "Hi there,",
      "",
      "[Personalised compliment based on review score / Instagram / location]",
      "",
      "I'm Mercier, founder of **Dentago** — a FREE platform that lets UK dental practices compare prices across all their suppliers (Henry Schein, Kent Express, Dental Sky, and 40+ others) in one place.",
      "",
      "Most practices we speak to are spending 3–5 hours a week on procurement and often overpaying by 15–30% simply because they don't have an easy way to compare. Dentago fixes that — no cost, no contract, just a faster and smarter way to buy.",
      "",
      "Would it be useful to see how it works for a practice like [Practice Name]? Happy to do a 15-min walkthrough — no sales pitch, just showing you the tool.",
      "",
      "Best,",
      "Mercier",
      "Dentago — www.dentago.co.uk",
    ].join("\n"),
  },
  {
    id: "clinic_EMAIL_02_follow_batch",
    title: "Clinic Email 2 — Follow-up (no reply, batch)",
    pickerHint: "~3 days after batch cold · softer · short call offer.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "~3 days after cold batch (Batches 1–3). Use when Email 1B or similar got no reply.",
    subject: "Re: Quick question for [Practice Name]",
    body: [
      "Hi there,",
      "",
      "Just following up on my email from a few days ago in case it got buried.",
      "",
      "I'm building Dentago — a free tool that lets UK dental practices compare prices across Henry Schein, Kent Express, Dental Sky and 40+ other suppliers in one place. Takes about 5 minutes to set up and most practices find they're overpaying somewhere.",
      "",
      "Worth a quick look? Happy to walk you through it on a short call — no commitment, just showing you the tool.",
      "",
      "Best,",
      "Mercier",
      "Dentago",
    ].join("\n"),
  },
  {
    id: "clinic_EMAIL_03_follow_personal",
    title: "Clinic Email 3 — Follow-up (personal, tight)",
    pickerHint: "4–5 days after Email 1 · one question.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "4–5 days after first personal outreach with no response. Keep ultra short.",
    subject: "Re: Free tool for [Practice Name]",
    body: [
      "Hi [First Name],",
      "",
      "Just following up on this — happy to keep it to 10 minutes if that's easier.",
      "",
      "One question: how long does your practice currently spend on ordering supplies each week?",
      "",
      "— Mercier",
    ].join("\n"),
  },
  {
    id: "clinic_EMAIL_04_final",
    title: "Clinic Email 4 — Final touch",
    pickerHint: "Last nudge · leave door open · link only.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "~5 days after Email 3, no reply. Last touch.",
    subject: "Re: Free tool for [Practice Name]",
    body: [
      "Hi [First Name],",
      "",
      "Last one from me — I know inboxes are busy.",
      "",
      "If procurement ever becomes a pain point, Dentago is free to try and takes 5 minutes to set up: www.dentago.co.uk",
      "",
      "— Mercier",
    ].join("\n"),
  },
  {
    id: "clinic_EMAIL_05_no_show",
    title: "Clinic Email 5 — Demo no-show",
    pickerHint: "They booked Calendly but didn’t show.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "Practice booked a demo and didn’t attend. Reschedule or async video.",
    subject: "Missed you — happy to reschedule",
    body: [
      "Hi [First Name],",
      "",
      "Looks like we missed each other — no problem at all. Happy to rebook whenever suits you.",
      "",
      "Here's my calendar: [calendly link]",
      "",
      "Or if you'd rather just see a quick overview first, I can send a 2-minute walkthrough video instead.",
      "",
      "— Mercier",
    ].join("\n"),
    warnings: ["Playbook says one CTA per email — pick calendar OR video, not both, for strict consistency."],
  },
  {
    id: "clinic_EMAIL_06_post_demo",
    title: "Clinic Email 6 — Post-demo",
    pickerHint: "Within ~2h of demo if not signed up.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "Within 2 hours after a demo if they haven’t completed signup.",
    subject: "Great speaking with you — next step",
    body: [
      "Hi [First Name],",
      "",
      "Really enjoyed speaking with you today. As promised — here's the signup link: [link]",
      "",
      "Takes about 5 minutes to connect your first supplier account. Once you've done that, try searching for something you order regularly and you'll see straight away whether you're getting the best price.",
      "",
      "Any questions, just reply here — I'm fast.",
      "",
      "— Mercier",
    ].join("\n"),
  },
  {
    id: "clinic_EMAIL_07_referral",
    title: "Clinic Email 7 — Referral ask",
    pickerHint: "Active clinic · 2+ orders · relationship warm.",
    groupId: "clinic_email",
    audience: "clinic",
    channel: "email",
    whenToUse: "Clinic has placed at least two orders — best moment to ask intros.",
    subject: "Quick favour — do you know anyone?",
    body: [
      "Hi [First Name],",
      "",
      "Really glad Dentago has been useful for [Practice Name].",
      "",
      "Quick ask — do you know any other practice managers who'd find this useful? Even one name would mean a lot at this stage of building.",
      "",
      "If anyone you refer signs up, I'll give you both 3 months of free analytics access (normally paid).",
      "",
      "— Mercier",
    ].join("\n"),
  },
  /* ── Demo watch (video-first) ─────────────────────────────────────── */
  {
    id: "demo_watch_guide",
    title: "Demo link · When to use (rules)",
    pickerHint: "Before using watch-link emails — paragraph-one discipline.",
    groupId: "clinic_demo_watch",
    audience: "internal",
    channel: "email",
    whenToUse:
      "Reference before sending clinic demo-first outreach. Primary CTA: https://www.dentago.co.uk/watch",
    body: [
      "Use when you want low friction — they watch (~2–4 min), then reply or book if interested.",
      "",
      "Cold paragraph-one must still:",
      "1. State plainly: free for clinics (disarm “another invoice”).",
      "2. Lead with their outcomes — time, bandwidth, spend clarity — not Dentago milestones.",
      "3. Scale the procurement problem honestly (portal fragmentation, duplication risk) — avoid fabricated £ savings vs their negotiated rates until integrations are proven.",
      "",
      "Subject lines that work: include [Practice Name] when you have it. Pick one:",
      "• [Practice Name] — ordering week still = five tabs?",
      "• [Practice Name] — who catches duplicate orders?",
      "• Still bouncing between supplier portals, [First Name]?",
      "• [Practice Name] — 4 min, no signup (procurement only)",
      "• Question for whoever runs ordering at [Practice Name]",
    ].join("\n"),
  },
  {
    id: "demo_watch_cold",
    title: "Demo link · Cold email",
    pickerHint: "Clinic cold · primary CTA = watch URL · no signup.",
    groupId: "clinic_demo_watch",
    audience: "clinic",
    channel: "email",
    whenToUse: "First touch when calendar is heavy — lead with demo URL.",
    subject: "[Practice Name] — ordering week still = five tabs?",
    body: [
      "Hi [First Name],",
      "",
      "Cold emails usually mean someone wants **money from the practice** — fair assumption — so I'll say this first: **Dentago is free for dental practices.** No subscription, no card, nothing invoiced by us on the clinic side.",
      "",
      "I'm writing because what we hear from managers isn't a minor tweak to ordering; it's **meaningful weekly time** burned across separate supplier portals, carts that don't line up, confirmations scattered across inboxes, and the nagging doubt someone already ordered the same SKU — plus spend that's harder to oversee than it should be. That competes directly with patient-facing work and proper financial control — not because teams are behind, but because almost nobody built tooling for multi-supplier dental buying.",
      "",
      "If that resonates, Dentago is UK-built for exactly that: **one workflow** to search and check out across distributors you already use, with **practice verification** before orders go through — how UK clinics actually buy, not a generic consumer checkout.",
      "",
      "**~2 minute walkthrough**, no signup:",
      "",
      "https://www.dentago.co.uk/watch",
      "",
      "If it doesn't match how you run procurement, ignore me; if it does, from there you'll be able to book a demo. And if even that takes too much time, just reply \"Yes\" and we'll get you onboarded via email.",
      "",
      "Mercier",
      "Founder, Dentago",
      "https://www.dentago.co.uk",
    ].join("\n"),
  },
  {
    id: "demo_watch_followup",
    title: "Demo link · Follow-up (3–5 days)",
    pickerHint: "No reply · bump once.",
    groupId: "clinic_demo_watch",
    audience: "clinic",
    channel: "email",
    whenToUse: "Single bump 3–5 days after demo-first cold.",
    subject: "Re: [Practice Name] — ordering week still = five tabs?",
    body: [
      "Hi [First Name],",
      "",
      "Sending this once — bad timing happens.",
      "",
      "Quick recap: **still zero cost to the practice**; the issue we're tackling is heavy weekly admin across supplier portals and messy multi-cart workflows — worth seeing once if that's ever painful.",
      "",
      "Same **4-minute** overview, no signup:",
      "",
      "https://www.dentago.co.uk/watch",
      "",
      "No reply needed if it's not a priority.",
      "",
      "Mercier",
      "Dentago",
    ].join("\n"),
  },
  {
    id: "demo_watch_warm",
    title: "Demo link · Warm / referral intro",
    pickerHint: "Someone referred them · credibility transfer.",
    groupId: "clinic_demo_watch",
    audience: "clinic",
    channel: "email",
    whenToUse: "Warm intros — mutual contact named in subject.",
    subject: "[Mutual contact] suggested I share this",
    body: [
      "Hi [First Name],",
      "",
      "[Mutual contact] thought this might save your team headaches — **Dentago doesn't charge clinics**; we're focused on cutting the tab-switching and fragmented ordering loop UK practices describe.",
      "",
      "Quick video:",
      "",
      "https://www.dentago.co.uk/watch",
      "",
      "Honest feedback welcome either way.",
      "",
      "Mercier",
      "Founder, Dentago",
      "https://www.dentago.co.uk",
    ].join("\n"),
  },
  {
    id: "demo_watch_li_dm",
    title: "Demo link · LinkedIn DM (micro)",
    pickerHint: "LinkedIn cold/warm DM · watch URL inline.",
    groupId: "clinic_demo_watch",
    audience: "clinic",
    channel: "linkedin",
    whenToUse: "LinkedIn when email isn’t appropriate — keep it short.",
    body:
      'Hi [First Name] — cold vendor pitches are exhausting; quick clarity: **Dentago is free for UK practices.** Built it around the weekly portal-hopping / duplicate-order drag managers describe. If relevant, 4-min watch (no signup): https://www.dentago.co.uk/watch — Mercier',
  },
  /* ── LinkedIn (Outreach Templates) ───────────────────────────────── */
  {
    id: "LI_cold_dm",
    title: "LinkedIn DM — Cold (first message)",
    pickerHint: "Connection request path · practice in [City].",
    groupId: "linkedin",
    audience: "clinic",
    channel: "linkedin",
    whenToUse: "First DM after connecting with PMs / principals. Not an email — keep short.",
    body:
      "Hi [First Name], I'm building Dentago — a free platform where UK dental practices compare prices across all their suppliers in one place and order from one cart. Saw you manage a practice in [City] and thought it might be useful. Worth a quick look?",
  },
  {
    id: "LI_post_accept",
    title: "LinkedIn DM — After accept (calendar)",
    pickerHint: "They accepted but didn’t reply.",
    groupId: "linkedin",
    audience: "clinic",
    channel: "linkedin",
    whenToUse: "They accepted connection, no reply yet. Offer 10-min + Calendly.",
    body:
      "Thanks for connecting [First Name]. Happy to show you Dentago in 10 minutes if you're curious — it's free for practices and connects to your existing supplier accounts. No new accounts to set up. Here's my calendar if useful: [calendly link]",
  },
  {
    id: "LI_building_public",
    title: "LinkedIn post — Building in public (weekly)",
    pickerHint: "Founder social · not a hard pitch.",
    groupId: "linkedin",
    audience: "clinic",
    channel: "social",
    whenToUse: "Weekly authentic update + early-access line for PMs.",
    body: [
      "[Week X of building Dentago]",
      "",
      "[One specific thing you learned, fixed, or discovered this week — from talking to a practice manager, from a bug you found, from a surprising data point]",
      "",
      "[One honest reflection — what's working, what isn't, what you're thinking about next]",
      "",
      "If you manage a UK dental practice and want early access: [link]",
    ].join("\n"),
  },
  /* ── Suppliers ───────────────────────────────────────────────────── */
  {
    id: "SUPPLIER_A",
    title: "Supplier A — Free distribution (SMB/mid)",
    pickerHint: "Dental Sky / DHB / Wrights / Trycare / DMI · 50+ clinics.",
    groupId: "supplier",
    audience: "supplier",
    channel: "email",
    whenToUse: "First contact with smaller dental distributors once 50+ active clinics barrier is met.",
    prerequisites: ["50+ active clinics minimum before supplier outreach policy."],
    subject: "Free distribution to [X] UK dental practices — Dentago",
    body: [
      "Hi [Name],",
      "",
      "I'm Mercier, founder of Dentago — a free procurement platform used by [X] UK dental practices to compare prices and place orders across all their suppliers in one place.",
      "",
      "I'd love [Company Name] to be part of it. No cost, no integration work required — just a CSV of your catalogue with current pricing. Your products get in front of every clinic on the platform from day one.",
      "",
      "Worth a 15-minute call this week?",
      "",
      "— Mercier, Founder, Dentago",
    ].join("\n"),
    warnings: ["If negotiating EDI/API instead of CSV, use Supplier C or bespoke thread — align with integrations team."],
  },
  {
    id: "SUPPLIER_B",
    title: "Supplier B — Leverage (HS / Kent only)",
    pickerHint: "Show search bleed + GMV · 200+ clinics.",
    groupId: "supplier",
    audience: "supplier",
    channel: "email",
    whenToUse: "Henry Schein & Kent Express only — when 200+ clinics and credible GMV / search narrative.",
    prerequisites: ["200+ clinics with real GMV data.", "Henry Schein or Kent Express only."],
    subject: "[X] UK clinics ordering without your catalogue connected",
    body: [
      "Hi [Name],",
      "",
      "I'm the founder of Dentago — a UK dental procurement marketplace with [X] verified practices actively comparing prices and placing orders through the platform.",
      "",
      "Every week, clinics search for products you carry and order alternatives because your catalogue isn't connected. That's [£X] in potential orders going elsewhere each month — I can show you the search volume data.",
      "",
      "I'm not asking for an integration or exclusivity. A CSV of your catalogue is all it takes to be visible to [X] UK clinics immediately.",
      "",
      "20 minutes this week?",
      "",
      "— Mercier, Founder, Dentago",
    ].join("\n"),
  },
  {
    id: "SUPPLIER_C",
    title: "Supplier C — Book 20 min (warm / technical)",
    pickerHint: "They replied · integration · NHS/framework · EDI.",
    groupId: "supplier",
    audience: "supplier",
    channel: "email",
    whenToUse:
      'After meaningful reply — “send details”, integration questions, NHS framework, EDI threads. Goal: ~20-minute slot. Lead with THEIR upside. Prefer a **concrete UK time** over a booking link when you want fewer hops.',
    subject: "Re: [last thread topic] — 20 minutes to align?",
    body: [
      "Hi [Name],",
      "",
      "For **[Company]**, the upside is simple: **another digital touchpoint where practices already shop** — without you funding a separate acquisition play. Managers compare and buy in one workflow; **your SKUs stay attributed to their existing account with you**, so we're additive, not a parallel channel that undercuts how you quote.",
      "",
      "On our side we'd use the time to **show you exactly how your range appears**, and to **square the technical path** (e.g. **EDI** onboarding, test vs prod, who owns catalogue/price refreshes) so your IT or ops team gets a crisp brief — not endless email ping-pong.",
      "",
      "**20 minutes.** No deck required on your side unless you want to bring one.",
      "",
      "Would **[day / date] at [time] UK** work for a quick video call (Teams / Meet)? If another slot suits you better, reply with what does and I'll send an invite.",
      "",
      "— Mercier, Founder, Dentago",
    ].join("\n"),
    warnings: [
      "Naming one concrete slot often gets faster replies than a Calendly link on supplier threads — always offer ‘or suggest alternatives’.",
    ],
  },
  /* ── Press ────────────────────────────────────────────────────────── */
  {
    id: "PRESS_launch",
    title: "Journalist — Launch",
    pickerHint: "Dentistry.co.uk · The Probe · practice magazines.",
    groupId: "press",
    audience: "press",
    channel: "email",
    whenToUse: "Launch announcements or journos covering dental SMB software.",
    subject: "New free procurement platform launches for UK dental practices",
    body: [
      "Hi [Name],",
      "",
      "I'm launching Dentago — a free platform that lets UK dental practices compare prices across all their suppliers and order from one cart.",
      "",
      "UK practices currently spend 3–4 hours a week logging into separate supplier websites, comparing prices manually, and placing individual orders. Dentago eliminates that. It connects to their existing supplier accounts — no new accounts, no setup cost, completely free for practices.",
      "",
      "Launching [date] with [X] practices already on the waitlist. Happy to offer you an exclusive first look or a quote for any piece you're working on.",
      "",
      "— Mercier, Founder, Dentago",
      "[phone number]",
    ].join("\n"),
  },
  /* ── Playbook ─────────────────────────────────────────────────────── */
  {
    id: "PLAYBOOK_notes",
    title: "Notes on what works (summary)",
    pickerHint: "Subject lines · length · timing · CTAs.",
    groupId: "playbook",
    audience: "internal",
    channel: "mixed",
    whenToUse: "Internal cheat sheet distilled from Outreach Templates — read periodically.",
    body: [
      "• Subject lines: specific beats clever. “[Practice Name]” wins vs generic subjects.",
      "• Length: under ~150 words for cold clinic email; follow-ups tighter (~50 words).",
      "• CTA: one ask per email. Multiple options add friction.",
      "• Timing: Tue–Thu, 8–9am or 12–1pm UK. Avoid Monday AM and Friday PM.",
      "• Follow-ups: replies often arrive on touch 2 or 3.",
      "• Personalisation: city, suppliers they use, concrete LinkedIn detail — generic reads as spam.",
      "• Clinic cold opener: assume they think you’re selling; front-load free for practice, their outcomes, real procurement load before product specs.",
      "• Batch logistics: chase non-responders per current cohort plan (see Outreach tab + weekly ops).",
    ].join("\n"),
  },
];

export function outreachTemplatesByGroup(id: OutreachTemplateGroupId): OutreachTemplate[] {
  return OUTREACH_TEMPLATES.filter((t) => t.groupId === id);
}
