/**
 * Decision Review — closes the decisions loop.
 *
 * Reads all decisions >7 days old with no recorded outcome.
 * Queries the events table for evidence of whether the expected outcome happened.
 * Uses Claude to assess prediction accuracy and suggests what to write as outcome.
 * Writes a review doc to Obsidian so you can fill in actual_outcome.
 *
 * Run:
 *   npx tsx scripts/os-decision-review.ts
 */

import Anthropic from "@anthropic-ai/sdk";
import * as fs from "fs";
import * as path from "path";

function loadEnv(file: string) {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]])
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}
loadEnv(path.resolve(__dirname, "..", ".env.local"));
loadEnv(path.resolve(__dirname, "..", ".env"));

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const OBSIDIAN_KEY = process.env.OBSIDIAN_API_KEY;
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

async function db(table: string, params = "") {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}${params}`, {
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}` },
  });
  return res.json();
}

async function main() {
  console.log("\n📋 Decision Review\n");

  const [decisions, events] = await Promise.all([
    db("decisions", "?select=*&order=created_at.asc"),
    db("events", "?select=event_type,payload,metrics,created_at&order=created_at.desc&limit=200"),
  ]);

  const decList = Array.isArray(decisions) ? decisions as any[] : [];
  const evList = Array.isArray(events) ? events as any[] : [];

  const unresolved = decList.filter((d: any) => {
    const ageD = (Date.now() - new Date(d.created_at).getTime()) / 86400000;
    return ageD > 7 && !d.actual_outcome;
  });

  console.log(`Total decisions: ${decList.length}`);
  console.log(`Unresolved (>7d, no outcome): ${unresolved.length}`);

  if (unresolved.length === 0) {
    console.log("All decisions have outcomes recorded. ✅");
    return;
  }

  const reviewItems: string[] = [];

  for (const d of unresolved) {
    const ageD = Math.round((Date.now() - new Date(d.created_at).getTime()) / 86400000);
    console.log(`\n🔍 Reviewing: "${d.decision.slice(0, 60)}..." (${ageD} days ago)`);

    const assessment = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 400,
      system: `You are reviewing a business decision to check if the expected outcome happened.
Look at the events data and give a brief assessment. Be specific. Use numbers from events if available.
Return a JSON object: { likely_accurate: boolean | null, evidence: string, suggested_outcome: string }
Return only valid JSON.`,
      messages: [{
        role: "user",
        content: `Decision (made ${ageD} days ago): ${d.decision}
Expected outcome: ${d.expected_outcome}
Rationale: ${d.rationale}

Recent business events:
${JSON.stringify(evList.slice(0, 50))}

Did the expected outcome happen? What does the evidence suggest?`,
      }],
    });

    let result = { likely_accurate: null as boolean | null, evidence: "Insufficient data", suggested_outcome: "Review manually" };
    try {
      const text = assessment.content[0].type === "text" ? assessment.content[0].text : "{}";
      const match = text.match(/\{[\s\S]*\}/);
      if (match) result = JSON.parse(match[0]);
    } catch { /* skip */ }

    const icon = result.likely_accurate === true ? "✅" : result.likely_accurate === false ? "❌" : "❓";
    console.log(`  ${icon} Evidence: ${result.evidence}`);
    console.log(`  Suggested outcome: ${result.suggested_outcome}`);

    reviewItems.push(`## Decision ${reviewItems.length + 1}: ${d.decision}

**Made:** ${new Date(d.created_at).toISOString().slice(0, 10)} (${ageD} days ago)
**Rationale:** ${d.rationale ?? "—"}
**Expected:** ${d.expected_outcome ?? "—"}

**AI Assessment:** ${icon} ${result.likely_accurate === true ? "Likely accurate" : result.likely_accurate === false ? "Likely inaccurate" : "Insufficient data"}
**Evidence:** ${result.evidence}
**Suggested outcome to record:** ${result.suggested_outcome}

> **ACTION:** Fill in actual outcome at dentago.co.uk/os → Decisions tab, or run:
> \`\`\`sql
> UPDATE decisions SET actual_outcome = '...', prediction_accurate = ${result.likely_accurate} WHERE id = '${d.id}';
> \`\`\`
`);
  }

  const content = `# Decision Review — ${new Date().toISOString().slice(0, 10)}

${unresolved.length} decision${unresolved.length > 1 ? "s" : ""} need outcome recorded.

${reviewItems.join("\n---\n\n")}

---
_Generated by os-decision-review.ts_
`;

  if (OBSIDIAN_KEY) {
    await fetch(`http://localhost:27123/vault/${encodeURIComponent(`Dentago/Intelligence/Decision Review — ${new Date().toISOString().slice(0, 10)}.md`)}`, {
      method: "PUT",
      headers: { Authorization: `Bearer ${OBSIDIAN_KEY}`, "Content-Type": "text/markdown" },
      body: content,
    }).catch(() => {});
    console.log("\n✅ Review written to Obsidian");
  } else {
    console.log("\n" + content);
  }
}

main().catch(e => { console.error(e); process.exit(1); });
