/**
 * Dentago OS — Daily Briefing Script
 * Reads all events from last 24h, computes KPIs, writes briefing to Obsidian.
 * Usage: npx tsx scripts/os-daily-briefing.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { createClient } from '@supabase/supabase-js';

function loadEnv(file: string) {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
loadEnv(path.resolve(__dirname, '..', '.env.local'));

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

async function main() {
  const today = new Date().toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString();

  // Pull all data
  const [clinics, events24h, decisions, loops, sentLog] = await Promise.all([
    supabase.from('clinic_profiles').select('id, status, created_at'),
    supabase.from('events').select('*').gte('created_at', yesterday).order('created_at', { ascending: false }),
    supabase.from('decisions').select('*').order('created_at', { ascending: false }).limit(5),
    supabase.from('loop_runs').select('*').gte('created_at', yesterday),
    fs.existsSync(path.join(process.env.HOME!, 'Downloads/dentago-sent-all.json'))
      ? JSON.parse(fs.readFileSync(path.join(process.env.HOME!, 'Downloads/dentago-sent-all.json'), 'utf8'))
      : { sent: [] },
  ]);

  const allClinics = clinics.data ?? [];
  const verified = allClinics.filter((c: any) => c.status === 'approved');
  const evts = events24h.data ?? [];
  const orders = evts.filter((e: any) => e.event_type === 'order_placed');
  const gmv24h = orders.reduce((s: number, e: any) => s + (e.payload?.order_value ?? 0), 0);
  const totalSent = (sentLog.sent ?? []).length;
  const suppliersConnected = evts.filter((e: any) => e.event_type === 'supplier_connected').length;

  // Event breakdown
  const eventBreakdown: Record<string, number> = {};
  for (const e of evts) {
    eventBreakdown[e.event_type] = (eventBreakdown[e.event_type] ?? 0) + 1;
  }

  const briefing = `# Dentago OS — Daily Briefing
**Date:** ${today}
**Generated:** ${new Date().toISOString()}

---

## Business State

| Metric | Value | KPI Target | Status |
|---|---|---|---|
| Total clinics | ${allClinics.length} | 50 by end May | ${allClinics.length >= 50 ? '✅' : '⏳'} |
| Verified clinics | ${verified.length} | — | — |
| Outreach contacts total | ${totalSent} | 15,000 this week | ${totalSent >= 15000 ? '✅' : '⏳'} |
| Orders placed (24h) | ${orders.length} | — | — |
| GMV (24h) | £${gmv24h.toFixed(2)} | £X/month | — |
| Supplier connections (24h) | ${suppliersConnected} | >70% of verified | — |

---

## Events (Last 24h)

${Object.entries(eventBreakdown).map(([k, v]) => `- **${k}:** ${v}`).join('\n') || '- No events logged'}

---

## Loop Runs (Last 24h)

${(loops.data ?? []).map((l: any) => `- **${l.loop_name}** — ${l.status} — KPIs: ${JSON.stringify(l.kpis_measured)}`).join('\n') || '- No loops ran in last 24h'}

---

## Recent Decisions

${(decisions.data ?? []).map((d: any) => `- **${d.decision}** (${d.created_at?.slice(0, 10)}) — Expected: ${d.expected_outcome}`).join('\n') || '- No decisions logged'}

---

## Attention Required

${orders.length === 0 ? '- ⚠️ No orders logged in 24h — GMV tracking may not be instrumented yet' : ''}
${verified.length < 10 ? '- ⚠️ Clinic count below 10 — acceleration needed' : ''}
${totalSent < 5000 ? '- ⚠️ Outreach volume low — target 15k by Tuesday' : ''}
${suppliersConnected === 0 && verified.length > 0 ? '- ⚠️ No supplier connections logged today — check /clinic/suppliers flow' : ''}

---

## Open Loops (Needs Human Decision)

Review and update [[CEO TODOs — 1 May 2026]] for any items that should be closed based on today's data.

---

*This briefing was auto-generated by the Dentago OS. All data from Supabase events table + outreach log.*
`;

  // Write to Obsidian via REST
  const obsidianUrl = 'http://localhost:27124';
  const apiKey = process.env.OBSIDIAN_API_KEY ?? '';
  const filePath = `Dentago/Intelligence/Daily Briefing — ${today}.md`;

  try {
    await fetch(`${obsidianUrl}/vault/${encodeURIComponent(filePath)}`, {
      method: 'PUT',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'text/markdown' },
      body: briefing,
    });
    console.log(`Briefing written to Obsidian: ${filePath}`);
  } catch {
    // Fallback: write locally
    console.log('Obsidian not reachable — writing to ~/Downloads/dentago-briefing.md');
    fs.writeFileSync(path.join(process.env.HOME!, 'Downloads/dentago-briefing.md'), briefing);
  }

  // Save KPI snapshot to Supabase
  await supabase.from('kpi_snapshots').insert({
    snapshot_date: today,
    kpis: {
      total_clinics: allClinics.length,
      verified_clinics: verified.length,
      outreach_total: totalSent,
      orders_24h: orders.length,
      gmv_24h: gmv24h,
      supplier_connections_24h: suppliersConnected,
    },
  });

  console.log('\nKPI Snapshot saved to Supabase');
  console.log(`Clinics: ${allClinics.length} total, ${verified.length} verified`);
  console.log(`Outreach: ${totalSent} total sent`);
  console.log(`GMV (24h): £${gmv24h.toFixed(2)}`);
}

main().catch(console.error);
