import pg from "pg";

const { Client } = pg;

const client = new Client({
  connectionString: "postgresql://postgres:hqyEzV9Po1o6rNS6@db.wybqjycfpauwlcrqgtfb.supabase.co:5432/postgres",
  ssl: { rejectUnauthorized: false },
});

await client.connect();
console.log("Connected to Supabase PostgreSQL");

// ── Create tables ────────────────────────────────────────────────────────────
await client.query(`
  CREATE TABLE IF NOT EXISTS dentago_suppliers (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    website TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS dentago_products (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT NOT NULL,
    image TEXT NOT NULL,
    description TEXT NOT NULL,
    pack_size TEXT NOT NULL,
    specs JSONB NOT NULL DEFAULT '[]',
    similars INTEGER[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS dentago_supplier_products (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES dentago_products(id) ON DELETE CASCADE,
    supplier_id INTEGER NOT NULL REFERENCES dentago_suppliers(id) ON DELETE CASCADE,
    price NUMERIC(10,2) NOT NULL,
    stock BOOLEAN NOT NULL DEFAULT TRUE,
    delivery TEXT NOT NULL,
    sku TEXT NOT NULL,
    pack_size TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, supplier_id)
  );

  CREATE INDEX IF NOT EXISTS idx_dentago_products_category ON dentago_products(category);
  CREATE INDEX IF NOT EXISTS idx_dentago_sp_product ON dentago_supplier_products(product_id);
  CREATE INDEX IF NOT EXISTS idx_dentago_sp_supplier ON dentago_supplier_products(supplier_id);
  CREATE INDEX IF NOT EXISTS idx_dentago_sp_stock ON dentago_supplier_products(stock);
`);
console.log("Tables created.");

// ── Suppliers ────────────────────────────────────────────────────────────────
const ALL_SUPPLIERS = [
  "Henry Schein", "Kent Express", "Dental Sky", "DHB", "Trycare",
  "DMI", "Wrights", "Clark Dental", "J&S Davis", "Patterson Dental",
  "Medentra", "Total Dental", "Amalgadent", "Nuvelo", "Dental Directory",
];

for (const name of ALL_SUPPLIERS) {
  await client.query(
    `INSERT INTO dentago_suppliers (name) VALUES ($1) ON CONFLICT (name) DO NOTHING`,
    [name]
  );
}
const { rows: suppliers } = await client.query(`SELECT id, name FROM dentago_suppliers`);
const supplierMap = Object.fromEntries(suppliers.map(s => [s.name, s.id]));
console.log(`${suppliers.length} suppliers ready.`);

// ── Products ─────────────────────────────────────────────────────────────────
const PRODUCTS = [
  { id:1, name:"Nitrile Examination Gloves — Large (Box of 100)", brand:"Cranberry", category:"PPE", image:"https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop&auto=format", packSize:"Box of 100", description:"Cranberry nitrile powder-free examination gloves offer superior puncture resistance and tactile sensitivity. AQL 1.5 rated, CE marked for medical use. Suitable for all dental procedures.", specs:[{label:"Size",value:"Large"},{label:"Quantity",value:"100 per box"},{label:"Material",value:"Nitrile"},{label:"Powder",value:"Powder Free"},{label:"AQL Rating",value:"1.5"},{label:"Colour",value:"Blue"},{label:"Certification",value:"CE Marked, EN455"}], similars:[2,3,4], suppliers:[{name:"Dental Sky",price:4.85,stock:true,delivery:"Next day",sku:"DS-NG-L100",packSize:"Box of 100"},{name:"DHB",price:4.95,stock:false,delivery:"5–7 days",sku:"DHB-N100L",packSize:"Box of 100"},{name:"Kent Express",price:5.20,stock:true,delivery:"2–3 days",sku:"KE-7821",packSize:"Box of 100"},{name:"Total Dental",price:5.30,stock:true,delivery:"2–3 days",sku:"TD-NGL100",packSize:"Box of 100"},{name:"Henry Schein",price:5.65,stock:true,delivery:"Next day",sku:"HS-401234",packSize:"Box of 100"}] },
  { id:2, name:"Nitrile Examination Gloves — Medium (Box of 100)", brand:"Cranberry", category:"PPE", image:"https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop&auto=format", packSize:"Box of 100", description:"Cranberry nitrile powder-free examination gloves in medium size. Same premium quality as our large variant.", specs:[{label:"Size",value:"Medium"},{label:"Quantity",value:"100 per box"},{label:"Material",value:"Nitrile"},{label:"Powder",value:"Powder Free"},{label:"AQL Rating",value:"1.5"},{label:"Colour",value:"Blue"},{label:"Certification",value:"CE Marked, EN455"}], similars:[1,3,4], suppliers:[{name:"Dental Sky",price:4.85,stock:true,delivery:"Next day",sku:"DS-NG-M100",packSize:"Box of 100"},{name:"Amalgadent",price:4.90,stock:true,delivery:"Next day",sku:"AM-NITRM100",packSize:"Box of 100"},{name:"Kent Express",price:5.10,stock:true,delivery:"2–3 days",sku:"KE-7820",packSize:"Box of 100"},{name:"Henry Schein",price:5.60,stock:true,delivery:"Next day",sku:"HS-401233",packSize:"Box of 100"},{name:"Nuvelo",price:5.75,stock:false,delivery:"3–5 days",sku:"NV-NGLM100",packSize:"Box of 100"}] },
  { id:3, name:"Type IIR Surgical Face Masks — Box of 50", brand:"Medicom", category:"PPE", image:"https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=800&h=600&fit=crop&auto=format", packSize:"Box of 50", description:"Medicom SafeMask Type IIR surgical face masks provide effective bacterial filtration (BFE ≥98%) and splash resistance.", specs:[{label:"Type",value:"Type IIR"},{label:"Quantity",value:"50 per box"},{label:"BFE",value:"≥98%"},{label:"Splash Resistant",value:"Yes"},{label:"Latex Free",value:"Yes"},{label:"Certification",value:"EN14683:2019"}], similars:[4,1,2], suppliers:[{name:"Clark Dental",price:3.20,stock:true,delivery:"Next day",sku:"CD-MASK50",packSize:"Box of 50"},{name:"Dental Sky",price:3.45,stock:true,delivery:"Next day",sku:"DS-MASK50",packSize:"Box of 50"},{name:"Amalgadent",price:3.50,stock:true,delivery:"Next day",sku:"AM-FMASK50",packSize:"Box of 50"},{name:"Kent Express",price:3.65,stock:true,delivery:"2–3 days",sku:"KE-5511",packSize:"Box of 50"},{name:"Henry Schein",price:3.80,stock:true,delivery:"Next day",sku:"HS-305021",packSize:"Box of 50"},{name:"Patterson Dental",price:3.90,stock:false,delivery:"4–5 days",sku:"PAT-FM50",packSize:"Box of 50"}] },
  { id:4, name:"FFP2 Respirator Masks — Box of 20", brand:"3M", category:"PPE", image:"https://images.unsplash.com/photo-1609220136736-443140cffec6?w=800&h=600&fit=crop&auto=format", packSize:"Box of 20", description:"3M FFP2 respirator masks filter at least 94% of airborne particles. Ideal for aerosol-generating procedures.", specs:[{label:"Rating",value:"FFP2"},{label:"Quantity",value:"20 per box"},{label:"Filtration",value:"≥94% NaCl/oil aerosol"},{label:"Exhalation Valve",value:"No"},{label:"Certification",value:"EN149:2001+A1:2009"}], similars:[3,1,2], suppliers:[{name:"Medentra",price:12.50,stock:true,delivery:"Next day",sku:"MED-FFP220",packSize:"Box of 20"},{name:"Dental Sky",price:13.10,stock:true,delivery:"Next day",sku:"DS-FFP220",packSize:"Box of 20"},{name:"Henry Schein",price:14.80,stock:true,delivery:"Next day",sku:"HS-3MFFP2",packSize:"Box of 20"},{name:"J&S Davis",price:14.95,stock:false,delivery:"5–7 days",sku:"JSD-FFP20",packSize:"Box of 20"}] },
  { id:5, name:"Septanest 4% Articaine + Epinephrine 1:100,000 — 50 Cartridges", brand:"Septodont", category:"Anaesthetics", image:"https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=600&fit=crop&auto=format", packSize:"50 cartridges × 1.7ml", description:"Septanest is the UK's leading dental anaesthetic. 4% articaine with 1:100,000 epinephrine provides rapid onset and profound anaesthesia.", specs:[{label:"Active Ingredient",value:"4% Articaine HCl"},{label:"Vasoconstrictor",value:"Epinephrine 1:100,000"},{label:"Quantity",value:"50 cartridges × 1.7ml"},{label:"Onset",value:"2–3 minutes"},{label:"Duration",value:"60–75 min (pulpal)"},{label:"pH",value:"3.5–4.5"}], similars:[6,7], suppliers:[{name:"Henry Schein",price:28.40,stock:true,delivery:"Next day",sku:"HS-189023",packSize:"50 cartridges"},{name:"Kent Express",price:29.80,stock:true,delivery:"2–3 days",sku:"KE-4421",packSize:"50 cartridges"},{name:"Dental Directory",price:30.50,stock:true,delivery:"2–3 days",sku:"DD-SEPT50",packSize:"50 cartridges"},{name:"Dental Sky",price:31.20,stock:false,delivery:"3–5 days",sku:"DS-SEP50",packSize:"50 cartridges"},{name:"Clark Dental",price:31.90,stock:true,delivery:"Next day",sku:"CD-SEPT50",packSize:"50 cartridges"}] },
  { id:6, name:"Lidocaine 2% + Epinephrine 1:80,000 — 50 Cartridges", brand:"Lignospan", category:"Anaesthetics", image:"https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&h=600&fit=crop&auto=format", packSize:"50 cartridges × 2.2ml", description:"Lignospan Standard provides reliable dental anaesthesia with 2% lidocaine HCl and 1:80,000 epinephrine.", specs:[{label:"Active Ingredient",value:"2% Lidocaine HCl"},{label:"Vasoconstrictor",value:"Epinephrine 1:80,000"},{label:"Quantity",value:"50 cartridges × 2.2ml"},{label:"Onset",value:"3–5 minutes"},{label:"Duration",value:"60–90 min (pulpal)"}], similars:[5,7], suppliers:[{name:"Wrights",price:22.10,stock:true,delivery:"Next day",sku:"WR-LIGN50",packSize:"50 cartridges"},{name:"Kent Express",price:23.40,stock:true,delivery:"2–3 days",sku:"KE-4400",packSize:"50 cartridges"},{name:"Henry Schein",price:24.90,stock:true,delivery:"Next day",sku:"HS-LIGN50",packSize:"50 cartridges"},{name:"Dental Directory",price:25.50,stock:false,delivery:"4–5 days",sku:"DD-LIGN50",packSize:"50 cartridges"}] },
  { id:7, name:"Ultracaine D-S Forte 4% Articaine — 50 Cartridges", brand:"Sanofi", category:"Anaesthetics", image:"https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=600&fit=crop&auto=format", packSize:"50 cartridges × 1.7ml", description:"Ultracaine D-S Forte by Sanofi contains 4% articaine with 1:100,000 adrenaline.", specs:[{label:"Active Ingredient",value:"4% Articaine HCl"},{label:"Vasoconstrictor",value:"Adrenaline 1:100,000"},{label:"Quantity",value:"50 cartridges × 1.7ml"},{label:"Onset",value:"2–4 minutes"}], similars:[5,6], suppliers:[{name:"Amalgadent",price:27.80,stock:true,delivery:"Next day",sku:"AM-ULTRA50",packSize:"50 cartridges"},{name:"Clark Dental",price:28.60,stock:true,delivery:"Next day",sku:"CD-ULTRA50",packSize:"50 cartridges"},{name:"Henry Schein",price:29.90,stock:true,delivery:"Next day",sku:"HS-ULTRA50",packSize:"50 cartridges"},{name:"Patterson Dental",price:30.40,stock:true,delivery:"3–4 days",sku:"PAT-ULTRA50",packSize:"50 cartridges"}] },
  { id:8, name:"3M ESPE Filtek Z250 Universal Restorative — A1 Syringe 4g", brand:"3M ESPE", category:"Consumables", image:"https://images.unsplash.com/photo-1588776814546-1ffedba86da3?w=800&h=600&fit=crop&auto=format", packSize:"4g syringe", description:"Filtek Z250 is a proven universal restorative composite with excellent polishability and marginal integrity.", specs:[{label:"Shade",value:"A1"},{label:"Weight",value:"4g syringe"},{label:"Type",value:"Micro-hybrid composite"},{label:"Radiopacity",value:"Yes (260% Al)"},{label:"Shrinkage",value:"1.9% volumetric"},{label:"Application",value:"Anterior & posterior"}], similars:[10,12,11,13], suppliers:[{name:"Wrights",price:17.90,stock:true,delivery:"Next day",sku:"WR-3MZ250A1",packSize:"4g syringe"},{name:"Henry Schein",price:18.75,stock:true,delivery:"Next day",sku:"HS-701892",packSize:"4g syringe"},{name:"Kent Express",price:19.40,stock:true,delivery:"2–3 days",sku:"KE-3M-A1",packSize:"4g syringe"},{name:"Nuvelo",price:20.10,stock:false,delivery:"5–7 days",sku:"NV-Z250A1",packSize:"4g syringe"}] },
  { id:9, name:"Dentsply Aquasil Ultra+ LV Regular Set — 50ml Cartridge", brand:"Dentsply Sirona", category:"Consumables", image:"https://images.unsplash.com/photo-1606811841689-23dfddce3e66?w=800&h=600&fit=crop&auto=format", packSize:"50ml cartridge", description:"Aquasil Ultra+ is a premium vinyl polysiloxane (VPS) impression material offering exceptional dimensional accuracy.", specs:[{label:"Viscosity",value:"Light / Monophase"},{label:"Volume",value:"50ml cartridge"},{label:"Set Time",value:"Regular (4.5 min)"},{label:"Working Time",value:"2 min 15 sec"},{label:"Shore A Hardness",value:"48"},{label:"Tear Strength",value:"3200 g/cm"}], similars:[8,10,12], suppliers:[{name:"DHB",price:41.80,stock:true,delivery:"2–3 days",sku:"DHB-AQU50",packSize:"50ml cartridge"},{name:"Henry Schein",price:42.60,stock:true,delivery:"Next day",sku:"HS-AQU-LV",packSize:"50ml cartridge"},{name:"Dental Sky",price:44.10,stock:true,delivery:"2–3 days",sku:"DS-AQULV",packSize:"50ml cartridge"},{name:"Dental Directory",price:45.20,stock:true,delivery:"3–4 days",sku:"DD-AQULV",packSize:"50ml cartridge"}] },
  { id:10, name:"Ketac Molar Easymix GIC — A3 Capsules x 50", brand:"3M ESPE", category:"Consumables", image:"https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&h=600&fit=crop&auto=format", packSize:"50 capsules", description:"Ketac Molar Easymix is a high-strength glass ionomer restorative for posterior teeth.", specs:[{label:"Shade",value:"A3"},{label:"Quantity",value:"50 capsules"},{label:"Type",value:"Glass ionomer (GIC)"},{label:"Fluoride Release",value:"Yes"},{label:"Self-Adhesive",value:"Yes"},{label:"Application",value:"Posterior restorations"}], similars:[12,8,11], suppliers:[{name:"Kent Express",price:54.20,stock:true,delivery:"2–3 days",sku:"KE-KETAM50",packSize:"50 capsules"},{name:"Henry Schein",price:56.80,stock:true,delivery:"Next day",sku:"HS-KETAC50",packSize:"50 capsules"},{name:"J&S Davis",price:57.40,stock:false,delivery:"5–7 days",sku:"JSD-KM50",packSize:"50 capsules"},{name:"Clark Dental",price:58.90,stock:true,delivery:"Next day",sku:"CD-KETAC50",packSize:"50 capsules"}] },
  { id:11, name:"Optibond FL Universal Bonding Agent — 4.5ml", brand:"Kerr", category:"Consumables", image:"https://images.unsplash.com/photo-1588776814546-1ffedba86da3?w=800&h=600&fit=crop&auto=format", packSize:"4.5ml primer + 4ml adhesive", description:"Optibond FL is the gold standard three-bottle bonding system.", specs:[{label:"Volume",value:"4.5ml primer + 4ml adhesive"},{label:"System",value:"Three-bottle (etch-and-rinse)"},{label:"Bond Strength",value:">30 MPa"},{label:"Filler Content",value:"15 wt% (adhesive)"},{label:"Cure",value:"Light cure"}], similars:[13,8,10], suppliers:[{name:"Trycare",price:24.60,stock:true,delivery:"Next day",sku:"TC-OPTFL45",packSize:"4.5ml + 4ml kit"},{name:"Wrights",price:25.40,stock:true,delivery:"Next day",sku:"WR-OPTFL",packSize:"4.5ml + 4ml kit"},{name:"Henry Schein",price:26.80,stock:true,delivery:"Next day",sku:"HS-OPTFL45",packSize:"4.5ml + 4ml kit"},{name:"Medentra",price:27.20,stock:true,delivery:"2–3 days",sku:"MED-OPTFL",packSize:"4.5ml + 4ml kit"},{name:"Total Dental",price:28.90,stock:false,delivery:"4–5 days",sku:"TD-OPTFL45",packSize:"4.5ml + 4ml kit"}] },
  { id:12, name:"Fuji IX GP Extra GIC Powder/Liquid — A2", brand:"GC", category:"Consumables", image:"https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&h=600&fit=crop&auto=format", packSize:"15g powder + 6.8ml liquid", description:"GC Fuji IX GP Extra is a high-strength glass ionomer cement.", specs:[{label:"Shade",value:"A2"},{label:"Format",value:"Powder + liquid"},{label:"Type",value:"High-strength GIC"},{label:"Compressive Strength",value:"270 MPa"},{label:"Fluoride Release",value:"Yes"}], similars:[10,8,13], suppliers:[{name:"Dental Directory",price:18.50,stock:true,delivery:"2–3 days",sku:"DD-FUJIA2",packSize:"15g + 6.8ml"},{name:"Amalgadent",price:19.20,stock:true,delivery:"Next day",sku:"AM-FUJIX",packSize:"15g + 6.8ml"},{name:"Henry Schein",price:20.40,stock:true,delivery:"Next day",sku:"HS-FUJIA2",packSize:"15g + 6.8ml"},{name:"Patterson Dental",price:21.10,stock:true,delivery:"3–4 days",sku:"PAT-FUJI",packSize:"15g + 6.8ml"}] },
  { id:13, name:"Clearfil SE Bond 2 — 6ml + 5ml Kit", brand:"Kuraray", category:"Consumables", image:"https://images.unsplash.com/photo-1588776814546-1ffedba86da3?w=800&h=600&fit=crop&auto=format", packSize:"6ml primer + 5ml bond", description:"Clearfil SE Bond 2 is a two-step self-etch bonding system.", specs:[{label:"Contents",value:"6ml primer + 5ml bond"},{label:"System",value:"Two-step self-etch"},{label:"Bond Strength (dentin)",value:"35 MPa"},{label:"MDP Monomer",value:"Yes"},{label:"Cure",value:"Light cure"}], similars:[11,8,12], suppliers:[{name:"Medentra",price:31.50,stock:true,delivery:"Next day",sku:"MED-CSE2",packSize:"6ml + 5ml kit"},{name:"Kent Express",price:32.80,stock:true,delivery:"2–3 days",sku:"KE-CSE2",packSize:"6ml + 5ml kit"},{name:"Henry Schein",price:34.90,stock:true,delivery:"Next day",sku:"HS-CLSEB2",packSize:"6ml + 5ml kit"}] },
  { id:14, name:"ProTaper Gold Rotary Files — F1 25mm (6 pcs)", brand:"Dentsply Sirona", category:"Endodontics", image:"https://images.unsplash.com/photo-1559839914-17aae19cec71?w=800&h=600&fit=crop&auto=format", packSize:"6 files", description:"ProTaper Gold combines gold metallurgy with the proven progressive-taper design.", specs:[{label:"File Type",value:"F1 (Finishing)"},{label:"Length",value:"25mm"},{label:"Quantity",value:"6 files"},{label:"Taper",value:"Progressive 0.07–0.05"},{label:"Alloy",value:"Gold thermally treated NiTi"},{label:"Tip Size",value:"#20"}], similars:[15,16,17], suppliers:[{name:"Trycare",price:32.50,stock:true,delivery:"Next day",sku:"TC-PTG-F1",packSize:"6 files"},{name:"DMI",price:33.10,stock:false,delivery:"5–7 days",sku:"DMI-PTGF1",packSize:"6 files"},{name:"Kent Express",price:34.00,stock:true,delivery:"2–3 days",sku:"KE-8811",packSize:"6 files"},{name:"Henry Schein",price:35.60,stock:true,delivery:"Next day",sku:"HS-PTG-F1",packSize:"6 files"}] },
  { id:15, name:"WaveOne Gold Primary — 25mm (3 pcs)", brand:"Dentsply Sirona", category:"Endodontics", image:"https://images.unsplash.com/photo-1559839914-17aae19cec71?w=800&h=600&fit=crop&auto=format", packSize:"3 files", description:"WaveOne Gold Primary is a single-file reciprocating system.", specs:[{label:"File Type",value:"Primary"},{label:"Length",value:"25mm"},{label:"Quantity",value:"3 files"},{label:"Motion",value:"Reciprocating"},{label:"Taper",value:"Variable 0.08–0.05"},{label:"Tip Size",value:"#25"}], similars:[14,16,17], suppliers:[{name:"Clark Dental",price:28.40,stock:true,delivery:"Next day",sku:"CD-WOG-P25",packSize:"3 files"},{name:"Trycare",price:29.10,stock:true,delivery:"Next day",sku:"TC-WOG-P",packSize:"3 files"},{name:"Henry Schein",price:30.80,stock:true,delivery:"Next day",sku:"HS-WOGP25",packSize:"3 files"},{name:"Nuvelo",price:31.50,stock:true,delivery:"2–3 days",sku:"NV-WOG25",packSize:"3 files"}] },
  { id:16, name:"Mineral Trioxide Aggregate (MTA) — 0.5g x 5 sachets", brand:"Dentsply Tulsa", category:"Endodontics", image:"https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&h=600&fit=crop&auto=format", packSize:"5 × 0.5g sachets", description:"ProRoot MTA is the gold standard for vital pulp therapy.", specs:[{label:"Quantity",value:"5 × 0.5g sachets"},{label:"Composition",value:"Calcium silicate"},{label:"Setting Time",value:"~3 hours"},{label:"pH",value:"12.5"},{label:"Radiopacity",value:"Yes"}], similars:[17,14,15], suppliers:[{name:"DHB",price:42.30,stock:true,delivery:"2–3 days",sku:"DHB-MTA5",packSize:"5 sachets"},{name:"Wrights",price:43.80,stock:true,delivery:"Next day",sku:"WR-MTA5",packSize:"5 sachets"},{name:"Henry Schein",price:45.90,stock:true,delivery:"Next day",sku:"HS-MTA5",packSize:"5 sachets"}] },
  { id:17, name:"Calasept Plus Calcium Hydroxide — 1.5ml Syringe x 4", brand:"Speident", category:"Endodontics", image:"https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&h=600&fit=crop&auto=format", packSize:"4 × 1.5ml syringes", description:"Calasept Plus is a pure calcium hydroxide paste for intracanal dressing.", specs:[{label:"Quantity",value:"4 × 1.5ml syringes"},{label:"Base",value:"Water-soluble"},{label:"pH",value:">12"},{label:"Radiopaque",value:"Yes"},{label:"Needles Included",value:"Yes"}], similars:[16,14,15], suppliers:[{name:"Amalgadent",price:8.40,stock:true,delivery:"Next day",sku:"AM-CALA4",packSize:"4 syringes"},{name:"Dental Directory",price:8.90,stock:true,delivery:"2–3 days",sku:"DD-CALA4",packSize:"4 syringes"},{name:"Kent Express",price:9.20,stock:true,delivery:"2–3 days",sku:"KE-CALA4",packSize:"4 syringes"},{name:"Henry Schein",price:9.80,stock:false,delivery:"4–5 days",sku:"HS-CALA4",packSize:"4 syringes"}] },
  { id:18, name:"Hu-Friedy Gracey Curette — SG1/2 (Standard)", brand:"Hu-Friedy", category:"Instruments", image:"https://images.unsplash.com/photo-1559839914-17aae19cec71?w=800&h=600&fit=crop&auto=format", packSize:"Single instrument", description:"Hu-Friedy SG1/2 Gracey Curettes are the industry standard for subgingival scaling.", specs:[{label:"Pattern",value:"SG1/2 (anterior)"},{label:"Handle",value:"Standard, round"},{label:"Material",value:"German stainless steel"},{label:"Sharpenable",value:"Yes"},{label:"Sterilisable",value:"Autoclavable"}], similars:[19,20], suppliers:[{name:"Clark Dental",price:18.50,stock:true,delivery:"Next day",sku:"CD-HFSG12",packSize:"Single"},{name:"J&S Davis",price:19.20,stock:true,delivery:"2–3 days",sku:"JSD-SG12",packSize:"Single"},{name:"Trycare",price:19.80,stock:true,delivery:"Next day",sku:"TC-SG12",packSize:"Single"},{name:"Henry Schein",price:21.40,stock:true,delivery:"Next day",sku:"HS-HFSG12",packSize:"Single"},{name:"Patterson Dental",price:22.10,stock:true,delivery:"3–4 days",sku:"PAT-SG12",packSize:"Single"}] },
  { id:19, name:"Stainless Steel Matrix Band — Tofflemire 0.035mm (Pack of 12)", brand:"Ivory", category:"Instruments", image:"https://images.unsplash.com/photo-1559839914-17aae19cec71?w=800&h=600&fit=crop&auto=format", packSize:"Pack of 12", description:"Ivory stainless steel Tofflemire matrix bands for universal retainers.", specs:[{label:"Gauge",value:"0.035mm"},{label:"Quantity",value:"12 bands"},{label:"Material",value:"Stainless steel"},{label:"Compatible",value:"Universal Tofflemire retainer"}], similars:[18,20], suppliers:[{name:"Dental Sky",price:2.40,stock:true,delivery:"Next day",sku:"DS-MBTOFF12",packSize:"Pack of 12"},{name:"Amalgadent",price:2.60,stock:true,delivery:"Next day",sku:"AM-TOFF12",packSize:"Pack of 12"},{name:"Kent Express",price:2.80,stock:true,delivery:"2–3 days",sku:"KE-TOFF12",packSize:"Pack of 12"},{name:"DMI",price:3.10,stock:true,delivery:"2–3 days",sku:"DMI-TOFF12",packSize:"Pack of 12"}] },
  { id:20, name:"Bard Parker Scalpel Handle — No. 3", brand:"BD", category:"Instruments", image:"https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&h=600&fit=crop&auto=format", packSize:"Single handle", description:"BD Bard-Parker No. 3 scalpel handle — industry standard for oral surgical procedures.", specs:[{label:"Handle No.",value:"No. 3"},{label:"Compatible Blades",value:"10, 11, 12, 15"},{label:"Material",value:"Stainless steel"},{label:"Sterilisable",value:"Autoclavable"}], similars:[18,19], suppliers:[{name:"Wrights",price:4.90,stock:true,delivery:"Next day",sku:"WR-BP3",packSize:"Single"},{name:"Medentra",price:5.20,stock:true,delivery:"Next day",sku:"MED-BP3",packSize:"Single"},{name:"Henry Schein",price:5.80,stock:true,delivery:"Next day",sku:"HS-BP3",packSize:"Single"}] },
  { id:21, name:"Optim 33 TB Surface Disinfectant Wipes — Tub of 160", brand:"SciCan", category:"Infection Control", image:"https://images.unsplash.com/photo-1584820927498-cad076df8735?w=800&h=600&fit=crop&auto=format", packSize:"Tub of 160 wipes", description:"Optim 33 TB wipes provide fast, effective surface disinfection in 1 minute contact time.", specs:[{label:"Quantity",value:"160 wipes per tub"},{label:"Contact Time",value:"1 minute"},{label:"Spectrum",value:"Bactericidal, virucidal, TB"},{label:"Alcohol Content",value:"Alcohol-free"},{label:"Surface Safe",value:"Yes (most materials)"}], similars:[22,23], suppliers:[{name:"Dental Directory",price:11.40,stock:true,delivery:"2–3 days",sku:"DD-OPT33-160",packSize:"160 wipes"},{name:"Dental Sky",price:11.90,stock:true,delivery:"Next day",sku:"DS-OPT33",packSize:"160 wipes"},{name:"Clark Dental",price:12.40,stock:true,delivery:"Next day",sku:"CD-OPT33",packSize:"160 wipes"},{name:"Henry Schein",price:13.20,stock:true,delivery:"Next day",sku:"HS-OPT33-160",packSize:"160 wipes"},{name:"Total Dental",price:13.80,stock:false,delivery:"4–5 days",sku:"TD-OPT33",packSize:"160 wipes"}] },
  { id:22, name:"Cavicide Surface Disinfectant Spray — 946ml", brand:"Metrex", category:"Infection Control", image:"https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&h=600&fit=crop&auto=format", packSize:"946ml bottle", description:"CaviCide is a ready-to-use intermediate-level surface disinfectant.", specs:[{label:"Volume",value:"946ml"},{label:"Contact Time",value:"3 minutes"},{label:"Active Ingredient",value:"Isopropanol + DDBAC"},{label:"Rinse Required",value:"No"},{label:"Fragrance",value:"Fragrance-free"}], similars:[21,23], suppliers:[{name:"Amalgadent",price:9.80,stock:true,delivery:"Next day",sku:"AM-CAVI946",packSize:"946ml"},{name:"DMI",price:10.20,stock:true,delivery:"2–3 days",sku:"DMI-CAVI946",packSize:"946ml"},{name:"Kent Express",price:10.80,stock:true,delivery:"2–3 days",sku:"KE-CAVI946",packSize:"946ml"},{name:"Patterson Dental",price:11.40,stock:true,delivery:"3–4 days",sku:"PAT-CAVI946",packSize:"946ml"}] },
  { id:23, name:"Stericlin Self-Seal Sterilisation Pouches — 90×135mm (Pack of 200)", brand:"Stericlin", category:"Infection Control", image:"https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800&h=600&fit=crop&auto=format", packSize:"Pack of 200", description:"Stericlin self-sealing sterilisation pouches with chemical indicators.", specs:[{label:"Size",value:"90 × 135mm"},{label:"Quantity",value:"200 per pack"},{label:"Compatible",value:"Steam, EO, formaldehyde"},{label:"Indicator",value:"Chemical indicator included"},{label:"Seal Type",value:"Self-sealing"},{label:"Certification",value:"CE, EN868-5"}], similars:[21,22], suppliers:[{name:"Nuvelo",price:6.90,stock:true,delivery:"2–3 days",sku:"NV-SS90200",packSize:"200 pouches"},{name:"Dental Sky",price:7.20,stock:true,delivery:"Next day",sku:"DS-SS90200",packSize:"200 pouches"},{name:"J&S Davis",price:7.50,stock:true,delivery:"2–3 days",sku:"JSD-SS90",packSize:"200 pouches"},{name:"Henry Schein",price:8.10,stock:true,delivery:"Next day",sku:"HS-STER90200",packSize:"200 pouches"}] },
  { id:24, name:"Straumann BLX Implant — 3.75mm × 10mm (RC)", brand:"Straumann", category:"Implants", image:"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800&h=600&fit=crop&auto=format", packSize:"Single implant", description:"Straumann BLX combines exceptional primary stability with broad indications.", specs:[{label:"Diameter",value:"3.75mm"},{label:"Length",value:"10mm"},{label:"Connection",value:"RC (Regular CrossFit)"},{label:"Surface",value:"SLActive"},{label:"Material",value:"Grade IV titanium"},{label:"Protocol",value:"Immediate / early loading"}], similars:[25,26], suppliers:[{name:"Henry Schein",price:148.00,stock:true,delivery:"Next day",sku:"HS-BLXRC3710",packSize:"Single"},{name:"Patterson Dental",price:152.00,stock:true,delivery:"3–4 days",sku:"PAT-BLX3710",packSize:"Single"},{name:"Clark Dental",price:154.50,stock:false,delivery:"5–7 days",sku:"CD-BLX3710",packSize:"Single"}] },
  { id:25, name:"Nobel Active Implant — 3.5mm × 11.5mm", brand:"Nobel Biocare", category:"Implants", image:"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800&h=600&fit=crop&auto=format", packSize:"Single implant", description:"Nobel Active features a unique conical implant body for exceptional primary stability.", specs:[{label:"Diameter",value:"3.5mm"},{label:"Length",value:"11.5mm"},{label:"Connection",value:"Internal tri-channel"},{label:"Surface",value:"TiUnite (oxidised)"},{label:"Material",value:"Grade IV titanium"},{label:"Protocol",value:"Immediate / delayed"}], similars:[24,26], suppliers:[{name:"Trycare",price:162.00,stock:true,delivery:"Next day",sku:"TC-NACC3511",packSize:"Single"},{name:"Henry Schein",price:168.00,stock:true,delivery:"Next day",sku:"HS-NA3511",packSize:"Single"},{name:"J&S Davis",price:171.50,stock:false,delivery:"7+ days",sku:"JSD-NA3511",packSize:"Single"}] },
  { id:26, name:"BioHorizons Tapered Internal Implant — 4.0mm × 12mm", brand:"BioHorizons", category:"Implants", image:"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800&h=600&fit=crop&auto=format", packSize:"Single implant", description:"BioHorizons Tapered Internal implants feature laser-lok micro-channels.", specs:[{label:"Diameter",value:"4.0mm"},{label:"Length",value:"12mm"},{label:"Connection",value:"Internal Morse taper"},{label:"Surface",value:"Laser-Lok + RBT"},{label:"Material",value:"Grade IV titanium"}], similars:[24,25], suppliers:[{name:"Dental Directory",price:98.00,stock:true,delivery:"2–3 days",sku:"DD-BH4012",packSize:"Single"},{name:"Medentra",price:102.00,stock:true,delivery:"Next day",sku:"MED-BH4012",packSize:"Single"},{name:"Henry Schein",price:109.00,stock:true,delivery:"Next day",sku:"HS-BH4012",packSize:"Single"}] },
  { id:27, name:"VistaScan Mini View Phosphor Plate — Size 2 (5 plates)", brand:"Dürr Dental", category:"Diagnostics", image:"https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&h=600&fit=crop&auto=format", packSize:"5 plates", description:"VistaScan phosphor plates deliver outstanding image quality.", specs:[{label:"Size",value:"Size 2 (standard)"},{label:"Quantity",value:"5 plates"},{label:"Reusable",value:"Up to 10,000 cycles"},{label:"Compatible Scanner",value:"Dürr VistaScan"},{label:"Thickness",value:"0.6mm"}], similars:[28], suppliers:[{name:"Clark Dental",price:42.80,stock:true,delivery:"Next day",sku:"CD-VSM-S2",packSize:"5 plates"},{name:"Henry Schein",price:44.50,stock:true,delivery:"Next day",sku:"HS-VSMS2",packSize:"5 plates"},{name:"Patterson Dental",price:46.00,stock:true,delivery:"3–4 days",sku:"PAT-VSM2",packSize:"5 plates"}] },
  { id:28, name:"Carestream Intraoral Sensor — Size 2 (Compatible)", brand:"Carestream", category:"Diagnostics", image:"https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&h=600&fit=crop&auto=format", packSize:"Single sensor", description:"Carestream RVG 6100 compatible digital intraoral sensor.", specs:[{label:"Size",value:"Size 2"},{label:"Pixel Size",value:"19.5 μm"},{label:"Resolution",value:"20 lp/mm"},{label:"Interface",value:"USB 2.0"},{label:"Image Format",value:"TWAIN compatible"}], similars:[27], suppliers:[{name:"DMI",price:820.00,stock:true,delivery:"3–5 days",sku:"DMI-CS-S2",packSize:"Single"},{name:"Henry Schein",price:860.00,stock:true,delivery:"Next day",sku:"HS-CSS2",packSize:"Single"},{name:"Nuvelo",price:895.00,stock:false,delivery:"7+ days",sku:"NV-CS-S2",packSize:"Single"}] },
  { id:29, name:"3M Unitek Transbond XT Light Cure Adhesive — 5ml Syringe", brand:"3M Unitek", category:"Orthodontics", image:"https://images.unsplash.com/photo-1606265752439-1f18756aa5fc?w=800&h=600&fit=crop&auto=format", packSize:"5ml syringe", description:"Transbond XT is the world's most-used orthodontic bonding adhesive.", specs:[{label:"Volume",value:"5ml syringe"},{label:"Cure",value:"Light cure (LED/halogen)"},{label:"Fluoride Release",value:"Yes"},{label:"Shear Bond Strength",value:">10 MPa"},{label:"Shade",value:"Opaque white"}], similars:[30], suppliers:[{name:"Trycare",price:28.40,stock:true,delivery:"Next day",sku:"TC-TBXT5",packSize:"5ml syringe"},{name:"Wrights",price:29.10,stock:true,delivery:"Next day",sku:"WR-TBXT5",packSize:"5ml syringe"},{name:"Henry Schein",price:30.80,stock:true,delivery:"Next day",sku:"HS-TBXT5",packSize:"5ml syringe"},{name:"Total Dental",price:31.50,stock:true,delivery:"2–3 days",sku:"TD-TBXT5",packSize:"5ml syringe"}] },
  { id:30, name:"Dentsply GAC Orthos Ceramic Brackets — MBT 0.022 (Pack of 10)", brand:"Dentsply GAC", category:"Orthodontics", image:"https://images.unsplash.com/photo-1606265752439-1f18756aa5fc?w=800&h=600&fit=crop&auto=format", packSize:"Pack of 10 brackets", description:"GAC Orthos ceramic brackets provide exceptional aesthetics.", specs:[{label:"Prescription",value:"MBT"},{label:"Slot Size",value:"0.022 inch"},{label:"Quantity",value:"10 brackets"},{label:"Material",value:"Monocrystalline ceramic"},{label:"Tie Wing",value:"Conventional"}], similars:[29], suppliers:[{name:"Amalgadent",price:54.00,stock:true,delivery:"Next day",sku:"AM-ORTHCER10",packSize:"Pack of 10"},{name:"Kent Express",price:56.80,stock:true,delivery:"2–3 days",sku:"KE-ORTHCER",packSize:"Pack of 10"},{name:"Henry Schein",price:59.40,stock:false,delivery:"5–7 days",sku:"HS-GACCER10",packSize:"Pack of 10"}] },
];

for (const p of PRODUCTS) {
  await client.query(
    `INSERT INTO dentago_products (id, name, brand, category, image, description, pack_size, specs, similars)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
     ON CONFLICT (id) DO UPDATE SET
       name=EXCLUDED.name, brand=EXCLUDED.brand, category=EXCLUDED.category,
       image=EXCLUDED.image, description=EXCLUDED.description, pack_size=EXCLUDED.pack_size,
       specs=EXCLUDED.specs, similars=EXCLUDED.similars, updated_at=NOW()`,
    [p.id, p.name, p.brand, p.category, p.image, p.description, p.packSize, JSON.stringify(p.specs), p.similars]
  );

  for (const s of p.suppliers) {
    const sid = supplierMap[s.name];
    if (!sid) { console.warn(`  ! Unknown supplier: ${s.name}`); continue; }
    await client.query(
      `INSERT INTO dentago_supplier_products (product_id, supplier_id, price, stock, delivery, sku, pack_size)
       VALUES ($1,$2,$3,$4,$5,$6,$7)
       ON CONFLICT (product_id, supplier_id) DO UPDATE SET
         price=EXCLUDED.price, stock=EXCLUDED.stock, delivery=EXCLUDED.delivery,
         sku=EXCLUDED.sku, pack_size=EXCLUDED.pack_size, updated_at=NOW()`,
      [p.id, sid, s.price, s.stock, s.delivery, s.sku, s.packSize ?? null]
    );
  }
  console.log(`  ✓ ${p.name.slice(0, 60)}`);
}

await client.end();
console.log("\nDatabase setup complete.");
